# Generated by Django 2.0.7 on 2018-07-29 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20180729_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='people'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_reg',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 4, 54, 35, 700876)),
        ),
    ]
